#encoding: utf-8

development:
  adapter: postgresql
  encoding: unicode
  database: faciscpop_development
  host: localhost #10.1.1.139
  pool: 5
  port: 5432
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  database: faciscpop_production
  host: localhost
  pool: 5
  port: 5432
  username: faciscpop
  password: <%= ENV['FACISCPOP_DATABASE_PASSWORD'] %>

#test:
#  adapter: postgresql
#  encoding: unicode
#  database: sigaemcloud_test
#  host: localhost
#  pool: 5
#  port: 5432
#  username: postgres
#  password: postgres
