development:
  adapter: postgresql
  encoding: unicode
  database: faciscpop_development
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: postgres

production:
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  port: 5432
  database: faciscpop_production
  username: faciscpop
  password: <%= ENV['faciscpop_DATABASE_PASSWORD'] %>
